# Generated by Django 2.2.2 on 2020-09-06 20:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='group_info_table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=122)),
                ('amount', models.CharField(max_length=6)),
            ],
        ),
    ]
