# Generated by Django 2.2.2 on 2020-09-06 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comity', '0003_group_info_table_created_by_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='group_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(max_length=6)),
                ('g_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comity.group_info_table')),
            ],
        ),
    ]
