# Generated by Django 2.2.2 on 2020-09-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comity', '0005_auto_20200906_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_table',
            name='start_comity',
            field=models.BooleanField(default=False),
        ),
    ]
