# Generated by Django 2.2.2 on 2020-10-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comity', '0008_auto_20200926_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_table',
            name='superuser',
            field=models.BooleanField(default=False),
        ),
    ]
