# Generated by Django 2.2.2 on 2020-10-16 20:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comity', '0010_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_info_table',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group_info_table',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
