# Generated by Django 2.2.2 on 2020-10-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comity', '0011_auto_20201016_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_info_table',
            name='created_at',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='group_info_table',
            name='updated_at',
            field=models.IntegerField(default=0),
        ),
    ]
