# Generated by Django 2.2.2 on 2020-11-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comity', '0013_group_table_bidamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_info_table',
            name='end_date',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group_info_table',
            name='start_date',
            field=models.IntegerField(default=0),
        ),
    ]
