# Generated by Django 2.2.2 on 2020-12-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comity', '0015_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_table',
            name='superuser',
        ),
        migrations.AddField(
            model_name='group_info_table',
            name='duration',
            field=models.CharField(default='1m', max_length=6),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='superuser',
            field=models.BooleanField(default=False),
        ),
    ]
