# Generated by Django 3.2.4 on 2021-06-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comity', '0017_alter_userinfo_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_table',
            name='round',
            field=models.IntegerField(default=0),
        ),
    ]
