# Generated by Django 3.2.4 on 2021-08-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comity', '0020_alter_group_table_u_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_info_table',
            name='status',
            field=models.CharField(default='inactive', max_length=12),
        ),
    ]
