# Generated by Django 3.2.4 on 2021-08-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comity', '0021_group_info_table_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_info_table',
            name='bid_date',
            field=models.IntegerField(default=0),
        ),
    ]
