# Generated by Django 3.2.4 on 2021-08-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comity', '0022_group_info_table_bid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='superuser_end_date',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='superuser_start_date',
            field=models.IntegerField(default=0),
        ),
    ]
