# Generated by Django 3.2.4 on 2021-08-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comity', '0023_auto_20210820_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_table',
            name='final_bid_time',
            field=models.IntegerField(default=0),
        ),
    ]
