# Generated by Django 3.2.4 on 2021-08-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comity', '0024_group_table_final_bid_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid_time',
        ),
        migrations.RemoveField(
            model_name='group_table',
            name='final_bid_time',
        ),
    ]
