# Generated by Django 3.2.4 on 2021-08-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comity', '0025_auto_20210820_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='gpay_qr_code',
            field=models.ImageField(blank=True, default='', upload_to='static/img/'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='paytm_qr_code',
            field=models.ImageField(blank=True, default='', upload_to='static/img/'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phonepe_qr_code',
            field=models.ImageField(blank=True, default='', upload_to='static/img/'),
        ),
    ]
