# Generated by Django 3.2.4 on 2021-08-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comity', '0027_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address_line_1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_line_2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
