# Generated by Django 3.2.4 on 2021-08-25 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comity', '0030_auto_20210825_2036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
