# Generated by Django 3.2.4 on 2021-08-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comity', '0031_delete_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gpay_qr_code',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
