# Generated by Django 3.2.4 on 2021-09-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comity', '0033_auto_20210828_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='razorpay_order_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='razorpay_signature',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
